/**
 * Actionable Alerts
 * Response workflows and actionable alert management
 */

export interface ActionableAlert {
  id: string;
  type: 'emergency' | 'safety' | 'health' | 'security' | 'system' | 'user_action' | 'reminder';
  priority: 'critical' | 'high' | 'medium' | 'low' | 'info';
  title: string;
  message: string;
  description: string;
  actions: Action[];
  context: {
    userId?: string;
    sessionId?: string;
    location?: {
      lat: number;
      lng: number;
      address?: string;
    };
    device?: {
      type: 'mobile' | 'tablet' | 'desktop' | 'wearable';
      batteryLevel: number;
      connectivity: string;
    };
    time: {
      timestamp: number;
      urgency: 'immediate' | 'urgent' | 'normal' | 'low';
      deadline?: number;
      timeRemaining?: number;
    };
    environment: {
      weather?: string;
      lighting?: string;
      noiseLevel?: string;
      connectivity?: string;
    };
  };
  status: {
    state: 'pending' | 'in_progress' | 'completed' | 'failed' | 'cancelled' | 'expired';
    createdAt: number;
    updatedAt: number;
    assignedTo?: string;
    assignedAt?: number;
    completedAt?: number;
    completedBy?: string;
    failureReason?: string;
    escalationLevel: number;
  };
  metadata: {
    category: string;
    tags: string[];
    severity: number; // 1-100
    confidence: number; // 0-100
    source: string;
    autoGenerated: boolean;
    expiresAt?: number;
    requiresConfirmation: boolean;
  confirmationCode?: string;
  };
  timestamp: number;
}

export interface Action {
  id: string;
  type: 'primary' | 'secondary' | 'tertiary' | 'emergency' | 'custom';
  title: string;
  description: string;
  icon?: string;
  url?: string;
  method: 'app' | 'web' | 'phone' | 'sms' | 'email' | 'voice' | 'location' | 'device' | 'system';
  parameters?: {
    [key: string]: any;
  };
  conditions: Array<{
    type: 'time' | 'location' | 'device' | 'user' | 'system' | 'context' | 'weather' | 'connectivity';
    field: string;
    operator: 'equals' | 'not_equals' | 'greater_than' | 'less_than' | 'in_range' | 'not_in_range' | 'contains' | 'not_contains';
    value: any;
    caseSensitive?: boolean;
  }>;
  autoExecute?: boolean;
  priority: number; // 1-10
  timeout?: number; // in seconds
  retryPolicy?: {
    maxAttempts: number;
    retryDelay: number; // in seconds
    backoffMultiplier: number;
  };
  successCriteria: {
    type: 'completion' | 'confirmation' | 'response' | 'acknowledgment' | 'dismissal';
    value?: any;
    timeout?: number; // in seconds
  };
  required: boolean;
  order: number; // Execution order
  dependencies: string[]; // Other action IDs that must complete first
}

export interface Workflow {
  id: string;
  name: string;
  description: string;
  version: string;
  isActive: boolean;
  category: 'emergency_response' | 'safety_monitoring' | 'health_management' | 'security_incident' | 'user_assistance' | 'automation';
  trigger: {
    type: 'manual' | 'automatic' | 'scheduled' | 'event_based' | 'condition_based';
    conditions?: Array<{
      field: string;
      operator: string;
      value: any;
    }>;
    alertType?: ActionableAlert['type'];
    priority?: ActionableAlert['priority'];
  };
  actions: Action[];
  steps: WorkflowStep[];
  settings: {
    autoExecute: boolean;
    requireConfirmation: boolean;
    timeout: number; // in seconds
    maxConcurrent: number;
    retryPolicy: {
      maxAttempts: number;
      retryDelay: number;
      backoffMultiplier: number;
    };
    notifications: {
      onCreate: boolean;
      onProgress: boolean;
      onCompletion: boolean;
      onFailure: boolean;
      onTimeout: boolean;
      templates: {
        [key: string]: {
          title: string;
          message: string;
          actions?: string[];
        };
      };
    };
  };
  createdAt: number;
  lastUsed: number;
  usageCount: number;
  successRate: number; // 0-100
  averageCompletionTime: number; // in seconds
}

export interface WorkflowStep {
  id: string;
  workflowId: string;
  name: string;
  description: string;
  type: 'action' | 'decision' | 'notification' | 'delay' | 'condition_check' | 'data_collection' | 'api_call' | 'system_update';
  order: number;
  actions: Action[];
  conditions: Array<{
    field: string;
    operator: string;
    value: any;
  }>;
  timeout?: number; // in seconds
  required: boolean;
  parallel?: boolean;
  dependencies: string[];
  onSuccess?: {
    stepId?: string;
    workflowId?: string;
  };
  onFailure?: {
    stepId?: string;
    workflowId?: string;
    retry?: boolean;
  };
  onTimeout?: {
    stepId?: string;
    workflowId?: string;
  };
  metadata: {
    [key: string]: any;
  };
}

export interface WorkflowExecution {
  id: string;
  workflowId: string;
  alertId: string;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'timeout';
  currentStep: number;
  startedAt: number;
  currentStepStartedAt: number;
  completedAt?: number;
  timeoutAt?: number;
  error?: string;
  results: {
    [stepId: string]: {
      status: 'pending' | 'completed' | 'failed' | 'skipped';
      result?: any;
      error?: string;
      startedAt: number;
      completedAt?: number;
      duration?: number;
      attempts: number;
    };
  };
  context: {
    userId?: string;
    sessionId?: string;
    location?: {
      lat: number;
      lng: number;
    };
    device?: {
      type: string;
      capabilities: string[];
    };
  };
  logs: Array<{
    timestamp: number;
    stepId: string;
    level: 'info' | 'warn' | 'error' | 'debug';
    message: string;
    data?: any;
  }>;
}

export interface ActionTemplate {
  id: string;
  name: string;
  description: string;
  category: 'emergency' | 'safety' | 'health' | 'security' | 'system';
  actions: Action[];
  conditions: Array<{
    type: string;
    field: string;
    operator: string;
    value: any;
  }>;
  isDefault: boolean;
  isActive: boolean;
  usageCount: number;
  successRate: number;
  lastUsed: number;
}

export class ActionableAlerts {
  private alerts: Map<string, ActionableAlert> = new Map();
  private workflows: Map<string, Workflow> = new Map();
  private executions: Map<string, WorkflowExecution> = new Map();
  private templates: Map<string, ActionTemplate> = new Map();
  private callbacks: Map<string, Function[]> = new Map();

  constructor() {
    this.loadAlerts();
    this.loadWorkflows();
    this.loadExecutions();
    this.loadTemplates();
    this.initializeDefaultWorkflows();
    this.initializeDefaultTemplates();
    this.startWorkflowMonitoring();
    this.startAlertProcessing();
    this.startExecutionMonitoring();
  }

  private loadAlerts(): void {
    try {
      const alerts = localStorage.getItem('resqai_actionable_alerts');
      if (alerts) {
        const alertData = JSON.parse(alerts);
        alertData.forEach((alert: ActionableAlert) => {
          this.alerts.set(alert.id, alert);
        });
      }
    } catch (error) {
      console.error('Failed to load alerts:', error);
    }
  }

  private loadWorkflows(): void {
    try {
      const workflows = localStorage.getItem('resqai_workflows');
      if (workflows) {
        const workflowData = JSON.parse(workflows);
        workflowData.forEach((workflow: Workflow) => {
          this.workflows.set(workflow.id, workflow);
        });
      }
    } catch (error) {
      console.error('Failed to load workflows:', error);
    }
  }

  private loadExecutions(): void {
    try {
      const executions = localStorage.getItem('resqai_workflow_executions');
      if (executions) {
        const executionData = JSON.parse(executions);
        executionData.forEach((execution: WorkflowExecution) => {
          this.executions.set(execution.id, execution);
        });
      }
    } catch (error) {
      console.error('Failed to load executions:', error);
    }
  }

  private loadTemplates(): void {
    try {
      const templates = localStorage.getItem('resqai_action_templates');
      if (templates) {
        const templateData = JSON.parse(templates);
        templateData.forEach((template: ActionTemplate) => {
          this.templates.set(template.id, template);
        });
      }
    } catch (error) {
      console.error('Failed to load templates:', error);
    }
  }

  private saveAlerts(): void {
    try {
      const alertData = Array.from(this.alerts.values());
      localStorage.setItem('resqai_actionable_alerts', JSON.stringify(alertData));
    } catch (error) {
      console.error('Failed to save alerts:', error);
    }
  }

  private saveWorkflows(): void {
    try {
      const workflowData = Array.from(this.workflows.values());
      localStorage.setItem('resqai_workflows', JSON.stringify(workflowData));
    } catch (error) {
      console.error('Failed to save workflows:', error);
    }
  }

  private saveExecutions(): void {
    try {
      const executionData = Array.from(this.executions.values());
      localStorage.setItem('resqai_workflow_executions', JSON.stringify(executionData));
    } catch (error) {
      console.error('Failed to save executions:', error);
    }
  }

  private saveTemplates(): void {
    try {
      const templateData = Array.from(this.templates.values());
      localStorage.setItem('resqai_action_templates', JSON.stringify(templateData));
    } catch (error) {
      console.error('Failed to save templates:', error);
    }
  }

  private initializeDefaultWorkflows(): void {
    if (this.workflows.size === 0) {
      const defaultWorkflows: Workflow[] = [
        {
          id: 'emergency_sos_workflow',
          name: 'Emergency SOS Response',
          description: 'Automated response workflow for SOS emergencies',
          version: '1.0',
          isActive: true,
          category: 'emergency_response',
          trigger: {
            type: 'event_based',
            alertType: 'emergency',
            priority: 'critical'
          },
          actions: [
            {
              id: 'notify_emergency_contacts',
              type: 'primary',
              title: 'Notify Emergency Contacts',
              description: 'Send immediate notifications to all emergency contacts',
              icon: 'contacts',
              method: 'app',
              parameters: { contacts: 'all', message: 'Emergency alert triggered' },
              order: 1,
              conditions: [],
              autoExecute: true,
              priority: 10,
              timeout: 30,
              required: true
            },
            {
              id: 'share_location',
              type: 'secondary',
              title: 'Share Location',
              description: 'Share current location with emergency services',
              icon: 'location',
              method: 'app',
              parameters: { services: ['emergency_services'], duration: 3600 },
              order: 2,
              conditions: [],
              autoExecute: false,
              priority: 8,
              timeout: 60,
              required: false
            },
            {
              id: 'call_emergency_services',
              type: 'tertiary',
              title: 'Call Emergency Services',
              description: 'Automatically call emergency services',
              icon: 'phone',
              method: 'phone',
              parameters: { number: '911' },
              order: 3,
              conditions: [
                {
                  type: 'user',
                  field: 'confirmation',
                  operator: 'equals',
                  value: true
                }
              ],
              autoExecute: false,
              priority: 9,
              timeout: 45,
              required: false
            }
          ],
          steps: [
            {
              id: 'step_1',
              workflowId: 'emergency_sos_workflow',
              name: 'Initialize Emergency Response',
              description: 'Initialize emergency response protocols',
              type: 'system_update',
              order: 1,
              actions: [
                {
                  id: 'activate_sos_mode',
                  type: 'system',
                  description: 'Activate SOS mode in all systems',
                  parameters: { mode: 'full' },
                  order: 1
                }
              ],
              required: true,
              timeout: 5
            },
            {
              id: 'step_2',
              workflowId: 'emergency_sos_workflow',
              name: 'Notify Emergency Contacts',
              description: 'Send notifications to emergency contacts',
              type: 'notification',
              order: 2,
              actions: [
                {
                  id: 'notify_contacts',
                  type: 'notification',
                  description: 'Send emergency notifications',
                  parameters: { 
                    template: 'emergency_contact_notification',
                    channels: ['push', 'sms'],
                    urgency: 'critical'
                  },
                  order: 1
                }
              ],
              dependencies: ['step_1'],
              required: true,
              timeout: 30
            },
            {
              id: 'step_3',
              workflowId: 'emergency_sos_workflow',
              name: 'Share Location',
              description: 'Share location with emergency services',
              type: 'location',
              order: 3,
              actions: [
                {
                  id: 'share_location',
                  type: 'location',
                  description: 'Share location with emergency services',
                  parameters: { 
                    services: ['emergency_services'],
                    duration: 3600,
                    accuracy: 'high'
                  },
                  order: 1
                }
              ],
              dependencies: ['step_2'],
              required: false,
              timeout: 60
            }
          ],
          settings: {
            autoExecute: true,
            requireConfirmation: false,
            timeout: 300,
            maxConcurrent: 1,
            retryPolicy: {
              maxAttempts: 3,
              retryDelay: 10,
              backoffMultiplier: 2
            },
            notifications: {
              onCreate: true,
              onProgress: true,
              onCompletion: true,
              onFailure: true,
              onTimeout: true
            }
          },
          createdAt: Date.now(),
          lastUsed: Date.now(),
          usageCount: 0,
          successRate: 95
        },
        {
          id: 'medical_emergency_workflow',
          name: 'Medical Emergency Response',
          description: 'Response workflow for medical emergencies',
          version: '1.0',
          isActive: true,
          category: 'health_management',
          trigger: {
            type: 'condition_based',
            conditions: [
              {
                type: 'context',
                field: 'health_emergency',
                operator: 'equals',
                value: true
              }
            ]
          },
          actions: [
            {
              id: 'collect_medical_info',
              type: 'data_collection',
              title: 'Collect Medical Information',
              description: 'Gather relevant medical data for emergency responders',
              icon: 'medical',
              method: 'app',
              parameters: { 
                info: ['conditions', 'medications', 'allergies', 'emergency_contacts'],
                format: 'emergency_response'
              },
              order: 1,
              conditions: [],
              autoExecute: true,
              priority: 10,
              timeout: 30,
              required: true
            },
            {
              id: 'share_medical_info',
              type: 'app',
              title: 'Share Medical Information',
              description: 'Share collected medical information with emergency services',
              icon: 'share',
              method: 'app',
              parameters: { 
                services: ['emergency_services', 'hospital'],
                format: 'medical_emergency'
              },
              order: 2,
              dependencies: ['collect_medical_info'],
              required: false,
              priority: 9,
              timeout: 60
            }
          ],
          steps: [
            {
              id: 'medical_step_1',
              workflowId: 'medical_emergency_workflow',
              name: 'Collect Medical Information',
              description: 'Gather medical information for emergency response',
              type: 'data_collection',
              order: 1,
              actions: [
                {
                  id: 'retrieve_conditions',
                  type: 'api_call',
                  description: 'Get medical conditions from profile',
                  parameters: { endpoint: '/medical/conditions' },
                  order: 1
                },
                {
                  id: 'retrieve_medications',
                  type: 'api_call',
                  description: 'Get current medications from profile',
                  parameters: { endpoint: '/medical/medications' },
                  order: 2
                },
                {
                  id: 'retrieve_allergies',
                  type: 'api_call',
                  description: 'Get allergies from profile',
                  parameters: { endpoint: '/medical/allergies' },
                  order: 3
                }
              ],
              required: true,
              timeout: 45
            },
            {
              id: 'medical_step_2',
              workflowId: 'medical_emergency_workflow',
              name: 'Share Medical Information',
              description: 'Share medical information with emergency services',
              type: 'app',
              order: 2,
              dependencies: ['medical_step_1'],
              actions: [
                {
                  id: 'format_medical_data',
                  type: 'system',
                  description: 'Format medical data for emergency services',
                  parameters: { 
                    format: 'emergency_response',
                    include: 'all'
                  },
                  order: 1
                },
                {
                  id: 'transmit_medical_data',
                  type: 'app',
                  description: 'Transmit medical data to emergency services',
                  parameters: { 
                    services: ['emergency_services', 'hospital'],
                    encrypted: true
                  },
                  order: 2
                }
              ],
              required: false,
              timeout: 60
            }
          ],
          settings: {
            autoExecute: false,
            requireConfirmation: true,
            timeout: 600,
            maxConcurrent: 1,
            retryPolicy: {
              maxAttempts: 2,
              retryDelay: 30,
              backoffMultiplier: 2
            },
            notifications: {
              onCreate: true,
              onProgress: true,
              onCompletion: true,
              onFailure: true
            }
          },
          createdAt: Date.now(),
          lastUsed: Date.now(),
          usageCount: 0,
          successRate: 90
        }
      ];

      defaultWorkflows.forEach(workflow => {
        this.workflows.set(workflow.id, workflow);
      });

      this.saveWorkflows();
    }
  }

  private initializeDefaultTemplates(): void {
    if (this.templates.size === 0) {
      const defaultTemplates: ActionTemplate[] = [
        {
          id: 'emergency_contact_template',
          name: 'Emergency Contact Notification',
          description: 'Template for notifying emergency contacts',
          category: 'emergency',
          actions: [
            {
              id: 'notify_primary',
              type: 'primary',
              title: 'Emergency Alert',
              description: 'Immediate notification required',
              icon: 'alert',
              method: 'app'
            },
            {
              id: 'notify_secondary',
              type: 'secondary',
              title: 'Emergency Follow-up',
              description: 'Follow-up notification',
              icon: 'info',
              method: 'app'
            }
          ],
          conditions: [
            {
              type: 'alert',
              field: 'priority',
              operator: 'equals',
              value: 'critical'
            }
          ],
          isDefault: true,
          isActive: true,
          usageCount: 0,
          successRate: 95
        },
        {
          id: 'medical_info_template',
          name: 'Medical Information Sharing',
          description: 'Template for sharing medical information',
          category: 'health',
          actions: [
            {
              id: 'share_summary',
              type: 'primary',
              title: 'Share Medical Summary',
              description: 'Share essential medical information',
              icon: 'medical',
              method: 'app'
            },
            {
              id: 'share_detailed',
              type: 'secondary',
              title: 'Share Full Medical Details',
              description: 'Share complete medical information',
              icon: 'medical',
              method: 'app'
            }
          ],
          conditions: [
            {
              type: 'user',
              field: 'consent',
              operator: 'equals',
              value: true
            }
          ],
          isDefault: true,
          isActive: true,
          usageCount: 0,
          successRate: 90
        }
      ];

      defaultTemplates.forEach(template => {
        this.templates.set(template.id, template);
      });

      this.saveTemplates();
    }
  }

  private startWorkflowMonitoring(): void {
    // Check for scheduled workflows every minute
    setInterval(() => {
      this.checkScheduledWorkflows();
    }, 60 * 1000);

    // Monitor workflow executions every 30 seconds
    setInterval(() => {
      this.monitorWorkflowExecutions();
    }, 30 * 1000);

    // Clean up old executions every hour
    setInterval(() => {
      this.cleanupOldExecutions();
    }, 60 * 60 * 1000);
  }

  private startAlertProcessing(): void {
    // Process alerts every 10 seconds
    setInterval(() => {
      this.processPendingAlerts();
    }, 10 * 1000);

    // Check for expired alerts every minute
    setInterval(() => {
      this.checkExpiredAlerts();
    }, 60 * 1000);
  }

  private startExecutionMonitoring(): void {
    // Monitor active executions every 5 seconds
    setInterval(() => {
      this.monitorActiveExecutions();
    }, 5 * 1000);
  }

  public async createActionableAlert(
    type: ActionableAlert['type'],
    priority: ActionableAlert['priority'],
    title: string,
    message: string,
    description: string,
    actions: Action[],
    context?: Partial<ActionableAlert['context']>,
    metadata?: Partial<ActionableAlert['metadata']>
  ): Promise<string> {
    const alertId = `actionable_alert_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    const alert: ActionableAlert = {
      id: alertId,
      type,
      priority,
      title,
      message,
      description,
      actions: this.validateActions(actions),
      context: {
        userId: 'current_user',
        sessionId: this.getSessionId(),
        ...context
      },
      time: {
        timestamp: Date.now(),
        urgency: this.determineUrgency(priority),
        deadline: this.calculateDeadline(priority)
      },
      status: {
        state: 'pending',
        createdAt: Date.now(),
        escalationLevel: 1
      },
      metadata: {
        category: this.determineCategory(type),
        tags: this.generateTags(type, priority),
        severity: this.calculateSeverity(priority),
        confidence: 90,
        source: 'system',
        autoGenerated: true,
        requiresConfirmation: priority === 'critical' || priority === 'high',
        ...metadata
      }
    };

    this.alerts.set(alertId, alert);
    this.saveAlerts();
    this.emit('actionableAlertCreated', alert);

    return alertId;
  }

  private validateActions(actions: Action[]): Action[] {
    return actions.filter(action => {
      return action.id && action.title && action.type && action.method;
    });
  }

  private determineUrgency(priority: ActionableAlert['priority']): ActionableAlert['time']['urgency'] {
    switch (priority) {
      case 'critical': return 'immediate';
      case 'high': return 'urgent';
      case 'medium': return 'normal';
      case 'low': return 'low';
      case 'info': return 'low';
      default: return 'normal';
    }
  }

  private calculateDeadline(priority: ActionableAlert['priority']): number {
    switch (priority) {
      case 'critical': return Date.now() + (5 * 60 * 1000); // 5 minutes
      case 'high': return Date.now() + (15 * 60 * 1000); // 15 minutes
      case 'medium': return Date.now() + (60 * 60 * 1000); // 1 hour
      case 'low': return Date.now() + (4 * 60 * 60 * 1000); // 4 hours
      case 'info': return Date.now() + (24 * 60 * 1000); // 24 hours
      default: return Date.now() + (2 * 60 * 60 * 1000); // 2 hours
    }
  }

  private determineCategory(type: ActionableAlert['type']): string {
    switch (type) {
      case 'emergency': return 'emergency_response';
      case 'safety': return 'safety_monitoring';
      case 'health': return 'health_management';
      case 'security': return 'security_incident';
      case 'system': return 'system_notification';
      case 'user_action': return 'user_activity';
      case 'reminder': return 'reminder_management';
      default: return 'general';
    }
  }

  private generateTags(type: ActionableAlert['type'], priority: ActionableAlert['priority']): string[] {
    const tags = [type, priority];
    
    if (type === 'emergency') {
      tags.push('immediate_action', 'auto_workflow');
    }
    
    if (priority === 'critical') {
      tags.push('requires_attention', 'auto_escalate');
    }

    return tags;
  }

  private calculateSeverity(priority: ActionableAlert['priority']): number {
    switch (priority) {
      case 'critical': return 100;
      case 'high': return 80;
      case 'medium': return 60;
      case 'low': return 40;
      case 'info': return 20;
      default: return 50;
    }
  }

  private getSessionId(): string {
    return `session_${Date.now()}`;
  }

  private async processPendingAlerts(): Promise<void> {
    const pendingAlerts = Array.from(this.alerts.values())
      .filter(alert => alert.status.state === 'pending');

    for (const alert of pendingAlerts) {
      try {
        await this.processAlert(alert);
      } catch (error) {
        console.error(`Error processing alert ${alert.id}:`, error);
        alert.status.state = 'failed';
        alert.status.failureReason = error instanceof Error ? error.message : 'Unknown error';
        alert.status.updatedAt = Date.now();
      }
    }

    this.saveAlerts();
  }

  private async processAlert(alert: ActionableAlert): Promise<void> {
    // Find matching workflow
    const workflow = await this.findMatchingWorkflow(alert);
    
    if (workflow) {
      await this.executeWorkflow(alert.id, workflow);
    } else {
      // No workflow found, create ad-hoc actions
      await this.executeAdHocActions(alert);
    }
  }

  private async findMatchingWorkflow(alert: ActionableAlert): Promise<Workflow | null> {
    const matchingWorkflows = Array.from(this.workflows.values())
      .filter(w => 
        w.isActive && 
        w.trigger.alertType === alert.type &&
        (!w.trigger.priority || w.trigger.priority === alert.priority)
      );

    // Sort by priority and usage
    matchingWorkflows.sort((a, b) => {
      const priorityScore = (b.successRate * 0.7) + (b.usageCount * 0.3);
      const aPriorityScore = (a.successRate * 0.7) + (a.usageCount * 0.3);
      return bPriorityScore - aPriorityScore;
    });

    return matchingWorkflows.length > 0 ? matchingWorkflows[0] : null;
  }

  private async executeWorkflow(alertId: string, workflow: Workflow): Promise<void> {
    const executionId = `execution_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    const execution: WorkflowExecution = {
      id: executionId,
      workflowId: workflow.id,
      alertId,
      status: 'running',
      currentStep: 0,
      startedAt: Date.now(),
      currentStepStartedAt: Date.now(),
      results: {}
    };

    this.executions.set(executionId, execution);
    this.saveExecutions();
    this.emit('workflowExecutionStarted', execution);

    try {
      await this.executeWorkflowSteps(workflow, execution);
    } catch (error) {
      execution.status = 'failed';
      execution.error = error instanceof Error ? error.message : 'Unknown error';
      execution.completedAt = Date.now();
      this.emit('workflowExecutionFailed', { execution, error });
    }
  }

  private async executeWorkflowSteps(workflow: Workflow, execution: WorkflowExecution): Promise<void> {
    for (const step of workflow.steps) {
      try {
        await this.executeStep(step, execution);
      } catch (error) {
        execution.results[step.id] = {
          status: 'failed',
          error: error instanceof Error ? error.message : 'Unknown error',
          startedAt: Date.now(),
          completedAt: Date.now(),
          duration: 0,
          attempts: 1
        };
        this.emit('workflowStepFailed', { step, execution, error });
      }
    }

    execution.status = 'completed';
    execution.completedAt = Date.now();
    this.saveExecutions();
    this.emit('workflowExecutionCompleted', execution);
  }

  private async executeStep(step: WorkflowStep, execution: WorkflowExecution): Promise<void> {
    const stepStartTime = Date.now();
    
    // Check conditions
    const conditionsMet = await this.evaluateStepConditions(step, execution);
    if (!conditionsMet) {
      execution.results[step.id] = {
        status: 'skipped',
        startedAt: stepStartTime,
        completedAt: Date.now(),
        duration: 0,
        attempts: 1
      };
      return;
    }

    execution.results[step.id] = {
      status: 'pending',
      startedAt: stepStartTime
    };

    // Execute actions
    for (const action of step.actions) {
      try {
        await this.executeAction(action, execution);
        execution.results[action.id] = {
          status: 'completed',
          result: 'Action completed successfully',
          startedAt: stepStartTime,
          completedAt: Date.now(),
          duration: Date.now() - stepStartTime,
          attempts: 1
        };
      } catch (error) {
        execution.results[action.id] = {
          status: 'failed',
          error: error instanceof Error ? error.message : 'Unknown error',
          startedAt: stepStartTime,
          completedAt: Date.now(),
          duration: Date.now() - stepStartTime,
          attempts: 1
        };
      }
    }

    // Check success criteria
    const stepSuccess = await this.evaluateStepSuccess(step, execution);
    if (stepSuccess) {
      execution.results[step.id].status = 'completed';
    } else {
      execution.results[step.id].status = 'failed';
    }
  }

  private async evaluateStepConditions(step: WorkflowStep, execution: WorkflowExecution): Promise<boolean> {
    if (!step.conditions || step.conditions.length === 0) {
      return true;
    }

    const alert = this.alerts.get(execution.alertId);
    if (!alert) return false;

    for (const condition of step.conditions) {
      const conditionMet = await this.evaluateCondition(condition, alert, execution);
      if (!conditionMet) {
        return false;
      }
    }

    return true;
  }

  private async evaluateCondition(
    condition: WorkflowStep['conditions'][0],
    alert: ActionableAlert,
    execution: WorkflowExecution
  ): Promise<boolean> {
    // This would evaluate the condition based on alert context and execution state
    // For now, return true for simplicity
    return true;
  }

  private async evaluateStepSuccess(step: WorkflowStep, execution: WorkflowExecution): Promise<boolean> {
    if (!step.successCriteria) {
      return execution.results[step.id]?.status === 'completed';
    }

    // Evaluate success criteria
    const criteria = step.successCriteria;
    if (criteria.type === 'completion') {
      return true;
    }

    // For other criteria types, would evaluate based on results
    return false;
  }

  private async executeAction(action: Action, execution: WorkflowExecution): Promise<void> {
    switch (action.method) {
      case 'app':
        await this.executeAppAction(action, execution);
        break;
      case 'web':
        await this.executeWebAction(action, execution);
        break;
      case 'phone':
        await this.executePhoneAction(action, execution);
        break;
      case 'sms':
        await this.executeSMSAction(action, execution);
        break;
      case 'email':
        await this.executeEmailAction(action, execution);
        break;
      case 'voice':
        await this.executeVoiceAction(action, execution);
        break;
      case 'location':
        await this.executeLocationAction(action, execution);
        break;
      case 'device':
        await this.executeDeviceAction(action, execution);
        break;
      case 'system':
        await this.executeSystemAction(action, execution);
        break;
    }
  }

  private async executeAppAction(action: Action, execution: WorkflowExecution): Promise<void> {
    console.log(`Executing app action: ${action.title}`);
    
    // This would integrate with the app's navigation or state management
    // For now, simulate the action
    this.emit('actionExecuted', { action, execution, method: 'app' });
  }

  private async executeWebAction(action: Action, execution: WorkflowExecution): Promise<void> {
    if (action.url) {
      console.log(`Opening web URL: ${action.url}`);
      // This would open the URL in a new tab or web view
      this.emit('actionExecuted', { action, execution, method: 'web' });
    }
  }

  private async executePhoneAction(action: Action, execution: WorkflowExecution): Promise<void> {
    const phoneNumber = action.parameters?.number;
    if (phoneNumber) {
      console.log(`Calling phone number: ${phoneNumber}`);
      // This would integrate with phone dialing API
      this.emit('actionExecuted', { action, execution, method: 'phone' });
    }
  }

  private async executeSMSAction(action: Action, execution: WorkflowExecution): Promise<void> {
    const phoneNumber = action.parameters?.number;
    const message = action.parameters?.message;
    
    if (phoneNumber && message) {
      console.log(`Sending SMS to ${phoneNumber}: ${message}`);
      // This would integrate with SMS service
      this.emit('actionExecuted', { action, execution, method: 'sms' });
    }
  }

  private async executeEmailAction(action: Action, execution: WorkflowExecution): Promise<void> {
    const email = action.parameters?.email;
    const subject = action.parameters?.subject;
    const body = action.parameters?.body;
    
    if (email && subject && body) {
      console.log(`Sending email to ${email}: ${subject}`);
      // This would integrate with email service
      this.emit('actionExecuted', { action, execution, method: 'email' });
    }
  }

  private async executeVoiceAction(action: Action, execution: WorkflowExecution): Promise<void> {
    const message = action.parameters?.message;
    
    if (message) {
      console.log(`Speaking message: ${message}`);
      // This would use text-to-speech
      this.emit('actionExecuted', { action, execution, method: 'voice' });
    }
  }

  private async executeLocationAction(action: Action, execution: WorkflowExecution): Promise<void> {
    console.log(`Executing location action: ${action.title}`);
    // This would integrate with location services
    this.emit('actionExecuted', { action, execution, method: 'location' });
  }

  private async executeDeviceAction(action: Action, execution: WorkflowExecution): Promise<void> {
    const deviceAction = action.parameters?.action;
    
    console.log(`Executing device action: ${deviceAction}`);
    // This would integrate with device APIs
    this.emit('actionExecuted', { action, execution, method: 'device' });
  }

  private async executeSystemAction(action: Action, execution: WorkflowExecution): Promise<void> {
    const systemCommand = action.parameters?.command;
    
    console.log(`Executing system action: ${systemCommand}`);
    // This would execute system-level commands
    this.emit('actionExecuted', { action, execution, method: 'system' });
  }

  private async executeAdHocActions(alert: ActionableAlert): Promise<void> {
    // Create ad-hoc actions from alert
    const adHocActions: Action[] = alert.actions.map((action, index) => ({
      id: `ad_hoc_${index}`,
      type: 'primary',
      title: action.title || `Action ${index + 1}`,
      description: action.description || `Execute action ${index + 1}`,
      method: 'app',
      order: index + 1,
      conditions: [],
      autoExecute: alert.priority === 'critical',
      priority: 10 - index,
      timeout: 30,
      required: index === 0
    }));

    // Execute ad-hoc actions
    for (const action of adHocActions) {
      try {
        await this.executeAction(action, {
          id: `ad_hoc_execution`,
          alertId: alert.id,
          status: 'pending',
          currentStep: 0,
          startedAt: Date.now(),
          currentStepStartedAt: Date.now(),
          results: {},
          context: {
            userId: alert.context.userId,
            sessionId: alert.context.sessionId
          },
          logs: []
        });
      } catch (error) {
        console.error(`Error executing ad-hoc action ${action.id}:`, error);
      }
    }
  }

  private async checkScheduledWorkflows(): Promise<void> {
    // This would check for scheduled workflows and trigger them
    // For now, it's a placeholder implementation
  }

  private async monitorWorkflowExecutions(): Promise<void> {
    const activeExecutions = Array.from(this.executions.values())
      .filter(execution => execution.status === 'running');

    for (const execution of activeExecutions) {
      // Check for timeouts
      if (execution.currentStepStartedAt && 
          Date.now() - execution.currentStepStartedAt > 300000) { // 5 minutes
        execution.status = 'timeout';
        execution.completedAt = Date.now();
        execution.error = 'Workflow execution timeout';
        this.emit('workflowExecutionTimeout', execution);
      }
    }
  }

  private cleanupOldExecutions(): void {
    const cutoffTime = Date.now() - (7 * 24 * 60 * 60 * 1000); // 7 days ago
    let cleanedCount = 0;
    
    for (const [id, execution] of this.executions) {
      if (execution.startedAt < cutoffTime) {
        this.executions.delete(id);
        cleanedCount++;
      }
    }
    
    if (cleanedCount > 0) {
      this.saveExecutions();
      this.emit('executionsCleaned', cleanedCount);
    }
  }

  private async checkExpiredAlerts(): Promise<void> {
    const now = Date.now();
    let expiredCount = 0;

    for (const [id, alert] of this.alerts) {
      if (alert.metadata.expiresAt && alert.metadata.expiresAt < now) {
        alert.status.state = 'expired';
        this.alerts.set(id, alert);
        expiredCount++;
      }
    }

    if (expiredCount > 0) {
      this.saveAlerts();
      this.emit('alertsExpired', expiredCount);
    }
  }

  public getActionableAlerts(
    type?: ActionableAlert['type'],
    status?: ActionableAlert['status']['state'],
    priority?: ActionableAlert['priority'],
    limit?: number
  ): ActionableAlert[] {
    let alerts = Array.from(this.alerts.values());

    if (type) {
      alerts = alerts.filter(alert => alert.type === type);
    }

    if (status) {
      alerts = alerts.filter(alert => alert.status.state === status);
    }

    if (priority) {
      alerts = alerts.filter(alert => alert.priority === priority);
    }

    alerts.sort((a, b) => {
      const priorityOrder = { critical: 4, high: 3, medium: 2, low: 1, info: 0 };
      const priorityDiff = priorityOrder[b.priority] - priorityOrder[a.priority];
      if (priorityDiff !== 0) return priorityDiff;
      return b.timestamp - a.timestamp;
    });

    return limit ? alerts.slice(0, limit) : alerts;
  }

  public getWorkflows(
    category?: Workflow['category'],
    activeOnly?: boolean,
    limit?: number
  ): Workflow[] {
    let workflows = Array.from(this.workflows.values());

    if (category) {
      workflows = workflows.filter(w => w.category === category);
    }

    if (activeOnly) {
      workflows = workflows.filter(w => w.isActive);
    }

    workflows.sort((a, b) => b.lastUsed - a.lastUsed);
    return limit ? workflows.slice(0, limit) : workflows;
  }

  public getWorkflowExecutions(
    workflowId?: string,
    status?: WorkflowExecution['status'],
    limit?: number
  ): WorkflowExecution[] {
    let executions = Array.from(this.executions.values());

    if (workflowId) {
      executions = executions.filter(e => e.workflowId === workflowId);
    }

    if (status) {
      executions = executions.filter(e => e.status === status);
    }

    executions.sort((a, b) => b.startedAt - a.startedAt);
    return limit ? executions.slice(0, limit) : executions;
  }

  public async acknowledgeAlert(alertId: string): Promise<boolean> {
    const alert = this.alerts.get(alertId);
    if (!alert) return false;

    alert.status.state = 'completed';
    alert.status.acknowledgedAt = Date.now();
    alert.status.completedAt = Date.now();

    this.alerts.set(alertId, alert);
    this.saveAlerts();
    this.emit('actionableAlertAcknowledged', alert);

    return true;
  }

  public async executeActionOnAlert(alertId: string, actionId: string): Promise<boolean> {
    const alert = this.alerts.get(alertId);
    if (!alert) return false;

    const action = alert.actions.find(a => a.id === actionId);
    if (!action) return false;

    try {
      const execution = {
        id: `manual_execution_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        workflowId: 'manual',
        alertId,
        status: 'running',
        currentStep: 0,
        startedAt: Date.now(),
        currentStepStartedAt: Date.now(),
        results: {},
        context: {
          userId: alert.context.userId,
          sessionId: alert.context.sessionId
        },
        logs: []
      };

      await this.executeAction(action, execution);
      
      this.executions.set(execution.id, execution);
      this.saveExecutions();
      this.emit('manualActionExecuted', { alert, action, execution });
      
      return true;
    } catch (error) {
      console.error(`Error executing action ${actionId}:`, error);
      return false;
    }
  }

  public getSystemStatus(): {
    totalAlerts: number;
    pendingAlerts: number;
    activeWorkflows: number;
    activeExecutions: number;
    successRate: number;
    averageCompletionTime: number;
  } {
    const alerts = Array.from(this.alerts.values());
    const pendingAlerts = alerts.filter(a => a.status.state === 'pending').length;
    const activeWorkflows = Array.from(this.workflows.values()).filter(w => w.isActive).length;
    const activeExecutions = Array.from(this.executions.values()).filter(e => e.status === 'running').length;

    return {
      totalAlerts: alerts.length,
      pendingAlerts,
      activeWorkflows,
      activeExecutions,
      successRate: this.calculateSuccessRate(),
      averageCompletionTime: this.calculateAverageCompletionTime()
    };
  }

  private calculateSuccessRate(): number {
    const completedExecutions = Array.from(this.executions.values())
      .filter(e => e.status === 'completed');

    if (completedExecutions.length === 0) return 0;

    const successCount = completedExecutions.length;
    const totalExecutions = Array.from(this.executions.values()).length;
    
    return Math.round((successCount / totalExecutions) * 100);
  }

  private calculateAverageCompletionTime(): number {
    const completedExecutions = Array.from(this.executions.values())
      .filter(e => e.status === 'completed' && e.completedAt);

    if (completedExecutions.length === 0) return 0;

    const totalTime = completedExecutions.reduce((sum, e) => 
      sum + (e.completedAt! - e.startedAt), 0
    );
    
    return Math.round(totalTime / completedExecutions.length / 1000); // in seconds
  }

  public on(event: string, callback: Function): void {
    if (!this.callbacks.has(event)) {
      this.callbacks.set(event, []);
    }
    this.callbacks.get(event)!.push(callback);
  }

  public off(event: string, callback: Function): void {
    const callbacks = this.callbacks.get(event);
    if (callbacks) {
      const index = callbacks.indexOf(callback);
      if (index > -1) {
        callbacks.splice(index, 1);
      }
    }
  }

  private emit(event: string, data: any): void {
    const callbacks = this.callbacks.get(event);
    if (callbacks) {
      callbacks.forEach(callback => {
        try {
          callback(data);
        } catch (error) {
          console.error(`Error in callback for event ${event}:`, error);
        }
      });
    }
  }

  public cleanup(): void {
    this.callbacks.clear();
    this.alerts.clear();
    this.workflows.clear();
    this.executions.clear();
    this.templates.clear();
  }
}
